steps:
  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "$$MY_SECRET" > src/main/resources/application.yml
    secretEnv: ['MY_SECRET']
  - name: gradle:8-jdk21
    entrypoint: gradle
    args: ["test"]
  - name: gradle:8-jdk21
    entrypoint: gradle
    args: ["assemble"]
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "$LOCATION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/hello-spring", "--build-arg=JAR_FILE=build/libs/hellospring-1.0.0.jar", "."]

# Secret Manager에서 비밀을 가져와 MY_SECRET 환경변수에 할당
availableSecrets:
  secretManager:
    - versionName: "projects/$PROJECT_ID/secrets/application-dev/versions/latest"
      env: "MY_SECRET"

options:
  logging: CLOUD_LOGGING_ONLY
  pool:
    name: 'projects/$PROJECT_ID/locations/$LOCATION/workerPools/workerpool'

images: ["$LOCATION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/hello-spring"]
