steps:
  - name: gradle:8-jdk17
    entrypoint: gradle
    args: ["test"]
  - name: gradle:8-jdk17
    entrypoint: gradle
    args: ["assemble"]
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "$LOCATION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/hello-spring", "--build-arg=JAR_FILE=build/libs/hellospring-1.0.0.jar", "."]

options:
  logging: CLOUD_LOGGING_ONLY

images: ["$LOCATION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/hello-spring"]