services:
  mysql:
    image: mysql:8.0.35
    container_name: mysql
    environment:
      MYSQL_DATABASE: 'core'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: '1234'
      MYSQL_ROOT_PASSWORD: '1234'
    ports:
      - "3306:3306"
    volumes:
      - 'mysqldata:/var/lib/mysql'

volumes:
  mysqldata: